#		CONFIG_XEN=y	
#	CONFIG_XEN_PV=y	
#	CONFIG_XEN_PV_SMP=y	
#	CONFIG_XEN_DOM0=y	
#	CONFIG_XEN_PVHVM=y	
#	CONFIG_XEN_PVHVM_SMP=y	
#	CONFIG_XEN_512GB=y	
#	CONFIG_XEN_SAVE_RESTORE=y	#
#	# CONFIG_XEN_DEBUG_FS is not set	
#	CONFIG_XEN_PVH=y