	MAKECONF () {  # /etc/portage/make.conf # https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
	NOTICE_START
		MAKECONF_VARIABLES () {
		NOTICE_START
			cat <<- EOF > /etc/portage/make.conf
			CC="$PRESET_CC"
			ACCEPT_KEYWORDS="$PRESET_ACCEPT_KEYWORDS"
			CHOST="$PRESET_CHOST_ARCH-$PRESET_CHOST_VENDOR-$PRESET_CHOST_OS-$PRESET_CHOST_LIBC"
			
			# (!NOTE) (!todo - not sure if this is "perfect" yet.. anyways, "it works". 
			CPU_FLAGS_X86="$PRESET_CPU_FLAGS_X86" # workaround to insert sse3 and sse4a - intentianal, no idea if requ - testing…
			# CPU_FLAGS_X86="$(lscpu | grep Flags: | sed -e 's/Flags:               //g')" # lscpu hides sse3 and sse4a which are shown in cpuid.
			CFLAGS="$PRESET_CFLAGS"
			CXXFLAGS="${PRESET_CFLAGS}"
			FCFLAGS="${PRESET_CFLAGS}"
			FFLAGS="${PRESET_CFLAGS}"
			MAKEOPTS="$PRESET_MAKE"
			EMERGE_DEFAULT_OPTS="$PRESET_EMERGE_DEFAULT_OPTS"
			INPUT_DEVICES="$PRESET_INPUTEVICE"
			VIDEO_CARDS="$PRESET_VIDEODRIVER"
			ACCEPT_LICENSE="$PRESET_LICENCES"
			FEATURES="$PRESET_FEATURES"
			USE="PLACEHOLDER_USEFLAGS"
			GENTOO_MIRRORS="$PRESET_GENTOMIRRORS"
			PORTDIR="$PRESET_PORTDIR"
			DISTDIR="$PRESET_DISTDIR"
			PKGDIR="$PRESET_PKGDIR"
			PORTAGE_TMPDIR="$PRESET_PORTAGE_TMPDIR"
			PORTAGE_LOGDIR="$PRESET_PORTAGE_LOGDIR"
			PORTAGE_ELOG_CLASSES="$PRESET_PORTAGE_ELOG_CLASSES"
			PORTAGE_ELOG_SYSTEM="$PRESET_PORTAGE_ELOG_SYSTEM"
			LINGUAS="$PRESET_LINGUAS"
			L10N="$PRESET_L10N"  # IETF language tags
			LC_MESSAGES="$PRESET_LC_MESSAGES"
			# CURL_SSL="$PRESET_CURL_SSL"
			NOCOLOR="true"
			EOF
			
			if [ $SYSAPP_DMCRYPT = "YES" ]; then
				echo "SYSAPP_DMCRYPT=YES"
				sed -ie "s/PLACEHOLDER_USEFLAGS/$PRESET_USEFLAG_CRYPTOPTANDCRYPTSETUP/g" /etc/portage/make.conf
			else
				echo "SYSAPP_DMCRYPT=NO"
				sed -ie "s/PLACEHOLDER_USEFLAGS/$PRESET_USEFLAG_LVMROOTNOCRYPOPT/g" /etc/portage/make.conf
			fi
		NOTICE_END
		}
		gcc -v
		cat /etc/portage/make.conf
		MAKECONF_VARIABLES
		cat /etc/portage/make.conf
		EMERGE_ATWORLD_B
	NOTICE_END
	}