	MISC1_CHROOT () {
		MISC1CHROOT_OPENRC () {
		NOTICE_START
			NOTICE_PLACEHOLDER
		NOTICE_END
		}
		MISC1CHROOT_SYSTEMD () {
		NOTICE_START
			systemctl preset-all
			systemctl daemon-reload
			ENVUD
		NOTICE_END
		}
		MISC1CHROOT_$SYSINITVAR
	NOTICE_END
	}