	SWAPFILE () {
	NOTICE_START
		DEBUG_SWAPFILE () {
		NOTICE_START
			swapon -s
			ls -lh $SWAPFD/$SWAPFILE_$SWAPSIZE
		NOTICE_END
		}
		CREATE_FILE () {
		NOTICE_START
			mkdir -p $SWAPFD
			fallocate -l $SWAPSIZE $SWAPFD/$SWAPFILE_$SWAPSIZE
			chmod 600 $SWAPFD/$SWAPFILE_$SWAPSIZE
			mkswap $SWAPFD/$SWAPFILE_$SWAPSIZE
		NOTICE_END
		}
		CREATE_SWAP () {
		NOTICE_START
			swapon  $SWAPFD/$SWAPFILE_$SWAPSIZE
		NOTICE_END
		}
		PERMANENT_SWAP () {
		NOTICE_START
			echo "$SWAPFD/$SWAPFILE_SWAPSIZE none swap sw 0 0" >> /etc/fstab
			cat /etc/fstab
		NOTICE_END
		}
		CREATE_FILE
		# DEBUG_SWAPFILE
		CREATE_SWAP
		# DEBUG_SWAPFILE
		# PERMANENT_SWAP
		df -h
	NOTICE_END
	}