# SYSLOGNG
SYSLOGNG_SYSLOG_SYSTEMD=syslog-ng@default
SYSLOGNG_SYSLOG_OPENRC=syslog-ng
SYSLOGNG_SYSLOG_EMERGE=app-admin/syslog-ng 
# SYSKLOGD
SYSKLOGD_SYSLOG_SYSTEMD=rsyslog
SYSKLOGD_SYSLOG_OPENRC=sysklogd
SYSKLOGD_SYSLOG_EMERGE=app-admin/sysklogd 
