	APP () {
	NOTICE_START
		APP_CRYPT () {
		NOTICE_START
			SYSAPP_GNUPG () {
			NOTICE_START
				# SETVAR_GNUPG
				APPAPP_EMERGE="app/crypt/gnupg "
				EMERGE_USERAPP_DEF
				gpg --full-gen-key
			NOTICE_END
			}
			SYSAPP_GNUPG
		NOTICE_END
		}
		APP_CRYPT
	NOTICE_END
	}