SYSAPP() {
	NOTICE_START
	SYSAPPS_PCIUTILS() {
		NOTICE_START
		APPAPP_EMERGE="sys-apps/pciutils "
		EMERGE_USERAPP_DEF
		NOTICE_END
	}
	SYSAPPS_FILEINDEXING() {
		NOTICE_START
		APPAPP_EMERGE="sys-apps/mlocate "
		EMERGE_USERAPP_DEF
		NOTICE_END
	}
	SYSAPPS_PCIUTILS
	SYSAPPS_FILEINDEXING
	NOTICE_END
}
