MAKECONF() { # /etc/portage/make.conf # https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
	NOTICE_START

	MAKECONF_VARIABLES() {
		NOTICE_START
		cat <<-EOF >/mnt/gentoo/etc/portage/make.conf
			CC="$PRESET_CC"
			ACCEPT_KEYWORDS="$PRESET_ACCEPT_KEYWORDS"
			CHOST="$PRESET_CHOST_ARCH-$PRESET_CHOST_VENDOR-$PRESET_CHOST_OS-$PRESET_CHOST_LIBC"

			CPU_FLAGS_X86="$(cpuid2cpuflags | cut -d: -f2 | xargs | cat -A)"
			# CPU_FLAGS_X86="$PRESET_CPU_FLAGS_X86"
			COMMON_FLAGS="$PRESET_COMMON_FLAGS"
			CONFIG_PROTECT="$PRESET_CONFIG_PROTECT"
			CFLAGS="${PRESET_COMMON_FLAGS}"
			CXXFLAGS="${PRESET_COMMON_FLAGS}"
			FCFLAGS="${PRESET_COMMON_FLAGS}"
			FFLAGS="${PRESET_COMMON_FLAGS}"
			LDFLAGS="$PRESET_LDFLAGS"
			RUSTFLAGS="$PRESET_RUSTFLAGS"
			MAKEOPTS="$PRESET_MAKE"
			EMERGE_DEFAULT_OPTS="$PRESET_EMERGE_DEFAULT_OPTS"
			INPUT_DEVICES="$PRESET_INPUTEVICE"
			VIDEO_CARDS="$PRESET_VIDEODRIVER"
			# Just a placeholder # VIDEO_CARDS="fbdev modesetting v4l vesa nvidia"
			ACCEPT_LICENSE="$PRESET_LICENCES"
			FEATURES="$PRESET_FEATURES"
			USE="PLACEHOLDER_USEFLAGS"
			GENTOO_MIRRORS="$PRESET_GENTOMIRRORS"
			PORTDIR="$PRESET_PORTDIR"
			DISTDIR="$PRESET_DISTDIR"
			PKGDIR="$PRESET_PKGDIR"
			PORTAGE_TMPDIR="$PRESET_PORTAGE_TMPDIR"
			PORTAGE_LOGDIR="$PRESET_PORTAGE_LOGDIR"
			PORTAGE_ELOG_CLASSES="$PRESET_PORTAGE_ELOG_CLASSES"
			PORTAGE_ELOG_SYSTEM="$PRESET_PORTAGE_ELOG_SYSTEM"
			LINGUAS="$PRESET_LINGUAS"
			L10N="$PRESET_L10N"
			LC_MESSAGES="$PRESET_LC_MESSAGES"
			# CURL_SSL="$PRESET_CURL_SSL"
			NOCOLOR="true"

		EOF

		local MOD

		#if [ "$CRYPTSETUP" = "YES" ]; then
		#	printf '%s\n' "CRYPTSETUP=YES"
		#	MOD=$(printf '%s\n' "$PRESET_USEFLAG_CRYPTSETUP")

		#else
		#	printf '%s\n' "CRYPTSETUP=NO"
		#	MOD=$(printf '%s\n' "$PRESET_USEFLAG_LVMROOT")

		#fi

		# conditional setup for cryptsetup or lvm on roo with desktop or server setup.
		case "${CRYPTSETUP}_${DSK_SRV}" in
			YES_DESKTOP)
				printf '%s\n' "CRYPTSETUP=YES PROFILE=DESKTOP"
				MOD="${PRESET_USEFLAG_CRYPTSETUP_DESKTOP}"
				;;
			YES_SERVER)
				printf '%s\n' "CRYPTSETUP=YES PROFILE=SERVER"
				MOD="${PRESET_USEFLAG_CRYPTSETUP_SERVER}"
				;;
			NO_DESKTOP)
				printf '%s\n' "CRYPTSETUP=NO PROFILE=DESKTOP"
				MOD="${PRESET_USEFLAG_LVMROOT_DESKTOP}"
				;;
			NO_SERVER)
				printf '%s\n' "CRYPTSETUP=NO PROFILE=SERVER"
				MOD="${PRESET_USEFLAG_LVMROOT_SERVER}"
				;;
			*)
				printf '%s\n' "Invalid combination: CRYPTSETUP=${CRYPTSETUP}, PROFILE=${DSK_SRV}"
				exit 1
				;;
		esac

		verify_or_exit "Update make.conf USE flags" \
			sed -i -e "s|PLACEHOLDER_USEFLAGS|$MOD|" "$CHROOTX/etc/portage/make.conf"

		NOTICE_END
	}

	MAKECONF_VARIABLES
	printf '%s\n' "/mnt/gentoo/etc/portage/make.conf"
	cat $CHROOTX/etc/portage/make.conf
	NOTICE_END
}
